mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/liy/**/mapper/*.xml


token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: Liy200110
  # 令牌存活时间：分钟
  expireTime: 60